### ISSUE TITLE
Works poorly with slight variations in background color

### ISSUE THREAD

**Issue by edvsjo** [edvsjo/photocropper#6]
The images with in the Only-Carol-Dress_383296_65 series has some slight variations in the background color. 
Possibly fixed by altering the stopping criteria in _only_contains() to be more leaniant.

**Comment by magnunm** [comment]
Tested out  0a40eb2 and it seems to fix the problems with finding the product when the background is not uniform, while not causing trouble in the other cases, great! :+1: 
Only thing I would change is to put the magic constant `20` in a variable, since we may want to tweak it later!

**Comment by edvsjo** [comment]
Yes that was a stupid oversight. Thanks for noticing!

**Comment by edvsjo** [comment]
As https://github.com/edvsjo/photocropper/pull/9 was merged this issue is solved
